---

- name: add Docker repo
  copy:
    dest="/etc/yum.repos.d/docker.repo"
    owner="root"
    group="root"
    mode=640
    src=docker.repo
    
- name: install docker-engine
  yum: name=docker-engine-1.10.3-1.el7.centos.x86_64 state=present
  become: True

- name: enable and start docker
  service: name=docker state=started enabled=yes

- name: set mount flags
  replace:
    dest=/usr/lib/systemd/system/docker.service
    regexp='^(.*)MountFlags=slave(.*)$'
    replace='MountFlags='
  sudo: true

- name: Reload systemctl
  command: systemctl daemon-reload
  
- name: Restart docker
  command: systemctl restart docker

- name: install git
  yum: name=git
  become: True
  
- name: checkout kube-deploy
  git: repo={{ repo }} dest=/home/vagrant/k8s-docker-provisioner version={{ version }} accept_hostkey=yes
  become: true
  become_user: vagrant
  become_method: sudo

- name: Create docker bootstrap service
  template:
    dest="/usr/lib/systemd/system/docker-bootstrap.service"
    owner=root
    group=root
    mode="640"
    src="docker-bootstrap.service.j2"

- name: Enable docker-bootstrap
  command: systemctl enable docker-bootstrap

- name: Start docker-bootstrap
  command: systemctl restart docker-bootstrap

